config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'polls#index' # 'application#hello'
  resources :polls do
    member do
      get :vote
      patch :submit
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  serialize :poll
  serialize :voted
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session # Null session to avoid development issues

  def hello
    render html: "Hello World!"
  end

  def goodbye
    render html: "Goodbye world!"
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def show
    @poll = Poll.find(params[:id])
    @total = 0
    @poll.poll.each do |key, poll|
      @total += poll[1]
    end
    if @total == 0
      @total = 1
    end
  end

  def vote
    @poll = Poll.find(params[:id])
  end

  def submit
    @poll = Poll.find(params[:id])
    if (!@poll.voted.include? request.remote_ip)
      @poll.poll[params["option"].to_i][1] = @poll.poll[params["option"].to_i][1] + 1
      @poll.voted.push(request.remote_ip)
      @poll.save
      redirect_to @poll
    else
      redirect_to vote_poll_path(@poll, error: '1')
    end
  end

  def create
    @poll = Poll.new(poll_params)
    if @poll.save
      redirect_to @poll
    else
      render 'new'
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy
    redirect_to polls_path
  end

  def update
    @poll = Poll.find(params[:id])
    update_params = poll_params
    if (@poll.update(update_params))
      redirect_to @poll
    else
      render 'edit'
    end
  end

  private
    def poll_params
      poll = Hash.new
      i = 0
      params["options"].each do |key, item|
        votes = 0
        if @poll
          @poll.poll.each do |key, val|
            if item == val[0]
              votes = val[1]
            end
          end
        end
        poll[i] = [item, votes]
        i+=1
      end

      params.require(:poll).permit(:title).merge(poll: poll).merge(voted: Array.new)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poll_helper.rb
module PollHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voterb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">VoteRB</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <%= link_to "New Poll", new_poll_path, :class => "nav-link" %>
          </li>
        </ul>
        <!-- TODO form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form-->
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_for(@poll, :html => {:class => "form-horizontal"}) do |f| %>

  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@poll.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @poll.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, :class => "control-label" %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div id="options">

  </div>

  <br>


  <button class="btn btn-block btn-info" type="button" name="button" onclick="add()">Add new option</button>
  <%= f.submit :class => "btn btn-block btn-success" %>

  <script type="text/javascript">

    var id;

    $(document).ready(function() {
      id = 0;
      <% if (@poll.poll) %>
        <% @poll.poll.each do |key, value| %>
          addOption("<%= value[0] %>");
        <% end %>
      <% else %>
        add();
      <% end %>
    });

    function add() {
      addOption("");
    }

    function addOption(val) {
      var html = "<div class='form-group' id='" + id + "'>";
      html += "<label style='float: left; margin-top: 3px; margin-bottom: 7px' for '" + id + "-input'control-label'>Option " + (id+1) + "</label>"
      if (id > 0) {
        html += "<div style='float: left; margin-bottom: 10px; margin-left: 10px'><button class='btn btn-sm btn-danger' type='button' name='button' onclick='$(\"#" + id + "\").remove()'>Delete option</button></div>";
      }
      html += "<input type='text' class='form-control' id='" + id + "-input' name='options[" + id + "]' value='" + val + "'>";
      html += "</div>"; // Class form-group
      $("#options").append(html);
      id++;
    }
  </script>
<% end %>

app/views/polls/edit.html.erb
<div class="jumbotron center"><h2>Edit Poll: <%= @poll.title %></h2></div>

<%= render 'form' %>

app/views/polls/index.html.erb

<div class="jumbotron center">
  <h1>Welcome to VoteRB</h1>
  <%= link_to 'Create new Poll', new_poll_path, :class => "btn btn-success btn-block btn-lg" %>
</div>
<p class="center">VoteRB is a voting system built on Rails. Click above to create a new poll or view one of the existing polls below.</p>
<table class="table table-striped table-hover">
  <tr>
    <th>Poll Name</th>
    <th></th>
    <th></th>
  </tr>
  <% @polls.each do |poll| %>
    <tr>
      <td><%= link_to poll.title, poll_path(poll), :class => "btn btn-info btn-block" %></td>
      <td><%= link_to "Edit Poll", edit_poll_path(poll), :class => "btn btn-success btn-block" %></td>
      <td><%= link_to "Delete Poll", poll_path(poll), method: :delete, data: { confirm: "Are you sure you want to delete this poll?" }, :class => "btn btn-danger btn-block" %></td>
    </tr>
  <% end %>
</table>

app/views/polls/new.html.erb
<div class="jumbotron center"><h2>New Poll</h2></div>

<%= render 'form' %>

app/views/polls/show.html.erb
<div class="jumbotron center">
  <h2><%= @poll.title %></h2>
</div>

<div class="results col-md-10 col-md-offset-1">
  <% @poll.poll.each do |key, value| %>
    <div class="result">
      <div class="row">
        <div class="col-md-10">
          <h4><strong><%= value[0] %></strong></h4>
        </div>
        <div class="col-md-2 center">
          <h4><strong>Votes: <%= value[1] %></strong></h4>
        </div>
      </div>
      <% percentage = Float(value[1]) / Float(@total) * 100 %>
      <div class="row">
        <div class="col-md-10">
          <div class="progress" style="height: 20px">
            <div class="progress-bar progress-bar-striped active progress-bar-success" style="width: <%= percentage %>%"></div>
          </div>
        </div>
        <div class="col-md-2 center">
          <%= percentage.round %>%
        </div>
      </div>
    </div>
  <% end %>
  <br>
</div>

<div class="row">
  <div class="col-md-3">
    <%= link_to 'Vote', vote_poll_path, :class => "btn btn-primary btn-block" %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Edit', edit_poll_path, :class => "btn btn-info btn-block" %>
  </div>
  <div class="col-md-3">
    <%= link_to "Delete", @poll, method: :delete, data: { confirm: "Are you sure you want to delete this poll?" }, :class => "btn btn-danger btn-block" %>
  </div>
  <div class="col-md-3">
    <%= link_to 'Back', polls_path, :class => "btn btn-primary btn-block" %>
  </div>
</div>

app/views/polls/vote.html.erb
<div class="jumbotron center">
  <h2>Voting on <%= @poll.title %> </h2>
</div>

<% if (params["error"] == "1") %>
  <div class="alert alert-danger">You have already voted on this poll!</div>
<% end %>

<%= form_for @poll, :url => {:action => 'submit'} do |f| %>
  <div class="form-group">
    <legend>Options</legend>
    <% @poll.poll.each do |key, value| %>
      <div class="form-check">
        <label class="form-check-label">
          <input class="form-check-input" type="radio" name="option" id="optionsRadios<%= key %>" value="<%= key %>">
          <%= value[0] %>
        </label>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.submit "Cast Vote", :class => "btn btn-success btn-block" %>
    </div>
    <div class="col-md-6">
      <%= link_to "Back to Poll", @poll, :class => "btn btn-primary btn-block" %>
    </div>
  </div>

<% end %>